package bo.gob.sin.sre.fac.frvcc.misfacturas.formularios.domain;


public class FormularioMother {

 /*   public static Formulario create(FormularioId id,
									FormularioTipoFormularioId tipoFormularioId,
									FormularioIfc ifc,
									FormularioNitCi nit,
									FormularioRazonSocial razonSocial,
									FormularioExpedicionCi expedicionCi,
									FormularioMesPeriodo mesPeriodo,
									FormularioAnioPeriodo anioPeriodo,
									FormularioNombreFormulario nombreFormulario,
									FormularioTotalCompras totalCompras,
									FormularioCantidadCompras cantidadCompras,
									FormularioLugarId lugarDepartamento,
									FormularioTipoPresentacionId tipoPresentacionId,
									FormularioDireccion direccion,
									FormularioNitEmpleador nitEmpleador,
									FormularioNombreEmpleador nombreEmpleador,
									FormularioDireccionEmpleador direccionEmpleador,
									FormularioEstadoFormularioId estadoFormularioId,
									FormularioNumeroEnvio numeroEnvio,
									FormularioFechaEstado fechaEstado,
									FormularioUsuarioRegistro usuarioRegistro,
									FormularioFechaRegistro fechaRegistro,
									FormularioUsuarioUltimaModificacion usuarioUltimaModificacion,
									FormularioFechaUltimaModificacion fechaUltimaModificacion,
									FormularioEstadoId estadoId,
									FormularioCodigoDependiente codigoDependiente,
									FormularioDeterminacionPago determinacionPago,
									FormularioFechaPresentacion fechaPresentacion,
									FormularioPeriodicidadId periodicidadId,
									FormularioCantidadPeriodicidad cantidadPeriodicidad,
									FormularioNumeroOrden numeroOrden) {
    	return new Formulario(
    			id,
				tipoFormularioId,
				ifc,
				nit,
				razonSocial,
				expedicionCi,
				mesPeriodo,
    			anioPeridodo,
				nombreFormulario,
				totalCompras,
				cantidadCompras,

				lugarId,
				tipoPresentacionId,
				direccion,
    			nitEmpleador,
				nombreEmpleador,
				direccionEmpleador,
				estadoFormularioId,
    			numeroEnvio,
				usuarioRegistro,
				fechaRegistro,
				usuarioUltimaModificacion,
    			fechaUltimaModificacion,
				estadoId,
				codigoDependiente,
				determinacionPago,
				fechaPresentacion,
				periodicidadId,
				cantidadPeriodicidad,
				numeroOrden);
    
    }
    public static Formulario fromRequest(CreateFormularioCommand request) {
        return Formulario.registro(FormularioIdMother.create(request.id()),
                FormularioTipoFormularioIdMother.create(request.tipoFormularioId()),
                FormularioIfcMother.create(request.ifc()),
                FormularioNitMother.create(request.nit()),
                FormularioMesPeriodoMother.create(request.mesPeriodo()),
                FormularioAnioPeriodoMother.create(request.anioPeriodo()),
                FormularioTipoPresentacionIdMother.create(request.tipoPresentacionId()),
                FormularioDireccionMother.create(request.direccion()),
                FormularioNitEmpleadorMother.create(request.nitEmpleador()),
                FormularioDireccionEmpleadorMother.create(request.direccionEmpleador()),
                FormularioNumeroEnvioMother.create(request.numeroEnvio()),
                FormularioUsuarioRegistroMother.create(request.usuarioRegistro()),
                FormularioRazonSocialMother.create(request.razonSocial()),
                FormularioNombreArchivoMother.create(request.nombreArchivo()),
                FormularioLugarIdMother.create(request.lugarId()),
                FormularioNombreEmpleadorMother.create(request.lugarId()),null,null,null,null,null);
    }

    public static Formulario whitId(String id) {
        return   create(FormularioIdMother.create(id),
                FormularioTipoFormularioIdMother.random(),
                FormularioIfcMother.random(),
                FormularioNitMother.random(),
                FormularioMesPeriodoMother.random(),
                FormularioAnioPeriodoMother.random(),
                FormularioTotalComprasMother.random(),
                FormularioCantidadComprasMother.random(),
                FormularioTotalVentasMother.random(),
                FormularioCantidadVentasMother.random(),
                FormularioTipoPresentacionIdMother.random(),
                FormularioDireccionMother.random(),
                FormularioNitEmpleadorMother.random(),
                FormularioDireccionEmpleadorMother.random(),
                FormularioEstadoFormularioIdMother.random(),
                FormularioNumeroEnvioMother.random(),
                FormularioUsuarioRegistroMother.random(),
                FormularioFechaRegistroMother.random(),
                FormularioUsuarioUltimaModificacionMother.random(),
                FormularioFechaUltimaModificacionMother.random(),
                FormularioEstadoIdMother.random(),
                FormularioRazonSocialMother.random(),
                FormularioNombreArchivoMother.random(),
                FormularioLugarIdMother.random(),
                FormularioNombreEmpleadorMother.random(),
                null,null,null,null,null,null
        		);
    }*/
}
